### ISSUE TITLE
Сломалась авторизация - http://vkontakte-on-rails.herokuapp.com/

### ISSUE THREAD

**Issue by targence** [7even/vkontakte_on_rails#1]
Сломалась авторизация тут - http://vkontakte-on-rails.herokuapp.com/

У меня на локальной машине процесс останавливается после переадресации с ВК обратно в приложение.

http://0.0.0.0:3000/?code=xxxxxxxxx&state=xxxxxxxxx

Дальше не идет. Предполагаю, что что-то поменялость в ВК

**Comment by 7even** [comment]
Не понял, сломалось на http://vkontakte-on-rails.herokuapp.com/ или в приложении, которое ты развернул локально?

**Comment by targence** [comment]
только тут - http://vkontakte-on-rails.herokuapp.com/
У себя уже разобрался, просто руки кривые =)

**Comment by 7even** [comment]
Странно, у меня работает на http://vkontakte-on-rails.herokuapp.com/, попробовал на 2 разных аккаунтах.

Судя по логам, твой токен не имеет прав на `friends.get`. А при авторизации спрашивает доступ к друзьям?

**Comment by targence** [comment]
хм, странно, теперь работает, сорри, за дезинформацию.

**Comment by djshafran** [comment]
# Gemfile
gem 'vkontakte_api', '~> 1.0', git : "https://github.com/7even/vkontakte_api.git"

потом
$ bundle install

так починится
