### ISSUE TITLE
автоматическая авторизация по аналогу topface.com

### ISSUE THREAD

**Issue by djshafran** [7even/vkontakte_on_rails#2]
Может быть общими усилиями сделаем так, что при заходе на сторонний сервер, вне нативного приложения Вконтакте (не standalone), судя по всему по токену в куках, получаем автозаход по полученной куке с номером пользователя.

**Comment by targence** [comment]
В смысле? Расскажи поподробнее? Пока звучит не оч. нужным =)

**Comment by djshafran** [comment]
Может так и есть, не очень это всё нужно, но приблуда в следующем:
На сколько я понял из своего короткого знакомства с Вконтакте АПИ, там есть несколько видов приложений.
vkontakte_on_rails - является отдельно стоящим приложением, и его внутри интерфейса vkontakte не увидишь. Или это не так? Если vkontake.ru даёт пользовать секьюрные методы после oauth авторизации, то можно понять что это уже внешнее приложение.
Теперь суть идеи заключается в том, чтобы скомбинировать интерфейсы встроенного приложения и внешнего, как это сделано у topface.com
Фактически это два rails сервера на разных портах одной машины. Первый работает как внутреннее приложение вконтакте, второй - как внешнее. Но они меняются между собой данными о пользователе через его куку.

Тяжело внятно что-то выразить, потому как совсем чуточку ещё с этим работал. Но достаточно зайти (установить) приложение topface, а потом зайти на сайт topface.com и всё станет ясно.

Вот такая идея, может быть совсем бесполезная. Но что-то мне кажется в ней есть, раз это реализовано у топфейса.

**Comment by targence** [comment]
@djshafran topface.com - это одно приложение ВК, не 2. Т.е. они просто исползуют iframe приложение для авторизации на сайте. Посмотри по id.

Никаких доп. фич. подобного рода не нужно =) есть просто особенности ВК, разных типов приложений, их нужно знать и использовать. Там не все логично, но как есть.

**Comment by djshafran** [comment]
**\* Как показать html теги?... я ламо в гитхабе, только с репозиториями работал, в обсуждениях не участвовал, просто смотрел что происходит, но решил попробовать вступить в процесс...

Это запрос topface с приложения vkontakte:
[iframe name="fXD3ea2d"....... src="http://vk.topface.com/?api_url=http://api.vk.com/api.php&amp;api_id=2257829&amp; ...; "][/iframe]

Сам топфейс открывается по topface.com без запроса к субдоменам, это как минимум означает что работа не в одном месте. В любом случае трафик от vkontakte.ru, фэйсбука и прямой вход - три разных входа. При том что кука при посещении вконтакта, или фейсбука по умолчанию для домена .topface.com не генерируется. Но поскольку опознание работает, при том обстоятельстве что при регистрации программы можно указать только один адрес для обращения к приложению, можно смело утверждать, что это разные программы одного сервера (или не одного), но приложения точно разные.

И в финале код запроса с фэйсбука для отправления данных по пользователю
[form action="http://fbapp.topface.com/?fb_source=bookmark_apps&amp;ref=bookmarks......"][/form]

**Comment by targence** [comment]
@djshafran  мне кажется нет смысла гадать, ни ты ни я не разработчик топфейса.
Они используют 1 приложение вк, не важно сколько у них серверов, доменов и пр. 
Это видно по id, остальное и тем более про fb уже вообще не важно.

**Comment by djshafran** [comment]
В принципе речь не о том, как там сделано, а сделать так же. 
Люди которые за 12 месяцев заработали аудиторию в 37 млн пользователей явно понимают какие фишки полезны. Общая аудитория Вконтакте по их данным сейчас 100 млн, а ему много лет. Поэтому, при всем уважении, очень бы хотелось услышать мнение автора этого приложения для работы с Вконтакте. Или получить ценные рекомендации на этот счёт в позитивном русле, которое поможет решить вопрос меньшей кровью.

Три метса для работы приложения topface [Facebook](http://apps.facebook.com/topface/?fb_source=bookmark_apps&ref=bookmarks&count=1&fb_bmpos=2_1), 
[Vkontakte](http://vk.com/app2257829) или [TopFace](http://topface.com/).

**Comment by 7even** [comment]
Никогда не писал iframe-приложения и весьма слабо представляю, как это делается.

По поводу авторизации - чем это отличается от нынешнего варианта? Токен и user_id и так хранятся в сессии. Разве что перенести их в вечную куку, т.к. сейчас после протухания сессии приходится авторизовываться по новой.

**Comment by djshafran** [comment]
Спасибо Вам, добрые люди. Начинаю кумекать немного. Как переварю - попробую выложить что получиться, вдруг кому пригодится. Спасибо ещё раз за участие.
