### ISSUE TITLE
Ошибка авторизации

### ISSUE THREAD

**Issue by Radzhab** [7even/vkontakte_on_rails#3]
В общем выдает ошибку {"error":"invalid_client","error_description":"client_id is incorrect"} при авторизации. Задеплойил на локальном сервере

**Comment by 7even** [comment]
Переменные окружения `APP_ID`, `APP_SECRET` и `REDIRECT_URI` передаются приложению?

Вообще работать все равно не будет, т.к. ВКонтакте запретили сайтам вызывать API-метод `newsfeed.get`.
