### ISSUE TITLE
Пишем по новой

### ISSUE THREAD

**Issue by beautyfree** [7even/vkontakte_on_rails#5]
Врятли для вас это новость - newsfeed уже нам не получить, пора переписывать демку, хотя бы без новостей иначе крашится.

**Comment by 7even** [comment]
Без новостей останется только список друзей, как-то негусто для демки.

У меня была задумка сделать нечто вроде фотохостинга на основе [vk](http://vk.com/dev/upload_files?f=%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%20%D1%84%D0%BE%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%B9%20%D0%B2%20%D0%B0%D0%BB%D1%8C%D0%B1%D0%BE%D0%BC%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F), можно взять за основу - но сейчас нет времени этим заниматься.

**Comment by Nutser** [comment]
@7even через АПИ сейчас можно стену получать - можно хотя бы так демку показать.

**Comment by beautyfree** [comment]
@Nutser проект уже мертв и не актуален по всей видимости)
